---
name: "Media Analyzer"
guid: "80885677-DACB-461B-AC97-EE7E971288AA"
version: "0.1.0.0"
targetAbi: "10.8.11"
framework: "net7.0"
overview: "Analyzes the audio of television episodes to detect intros."
description: >
  Analyzes the audio of television episodes to detect intros.
category: "General"
owner: "jellyfin"
artifacts:
  - "Jellyfin.Plugin.MediaAnalyzer.dll"
changelog: >
  changelog
